name: Docker Bench Security

on:
  push:
    branches:
      - main  # O la rama en la que quieras ejecutar el flujo de trabajo

jobs:
  run-docker-bench:
    runs-on: ubuntu-latest  # Puedes cambiar a windows-latest si prefieres usar Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Bench Security
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd):/docker-bench-security \
          docker/docker-bench-security > report_$(date +'%Y%m%d_%H%M%S').txt
          
      - name: List files to verify report
        run: ls -l

      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-bench-security-report
          path: report_*.txt
